.TH REF_LECT 1 "04 Jui 2012"
.SH NAME
erawrim\fP \- Mir:ror application launcher

.SH SYNOPSIS
.B erawrim
.SH DESCRIPTION
.B erawrim
is an application launcher for
.B ref-lect
the user space driver for
.B Mir:ror
RFID USB device.
It translates all events (RFID tag in and out, device flipped
up or down) into script calls.
.P
This program must be run in background by user.
For example, it can be activated at session starting.
.SH FILES
.B $HOME/.erawrim
the root database
.P
.B $HOME/.erawrim/log
the log file
.P
.B $HOME/.erawrim/annuaire
the aliases between RFID id and symbolic names given by user
.P
.B $HOME/.erawrim/ztamps/
this directory contains the id of currently visible ztamps
.P
.B $HOME/.erawrim/endroit.sh
the script called when
.B Mir:ror
is flipped up
.P
.B $HOME/.erawrim/envers.sh
the script called when
.B Mir:ror
is flipped down
.P
.B $HOME/.erawrim/<ztamp_alias>/pose.sh
the script called when the associated ztamp is put
.P
.B $HOME/.erawrim/<ztamp_alias>/retire.sh
the script called when the associated ztamp is poped
.P
.B $HOME/.erawrim/<ztamp_alias>/times
the number of times the associated ztamp was inserted
.P
.B $HOME/.erawrim/<ztamp_alias>/lasttime
the timestamp of the last insertion of the associated ztamp
.P
.B $HOME/.erawrim/defaut/pose.sh
the script called when an unknown ztamp is put
.P
.B $HOME/.erawrim/defaut/retire.sh
the script called when an unknown ztamp is poped
.SH AUTHORS
Guilhem Bonnefille  <guilhem.bonnefille@gmail.com>

