.TH REF_LECT 1 "04 Jui 2012"
.SH NAME
erawrim\fP \- Mir:ror application launcher

.SH SYNOPSIS
.B erawrim
.SH DESCRIPTION
.B erawrim
is an application launcher for
.B ref-lect
the user space driver for
.B Mir:ror
RFID USB device.
It translates all events (RFID tag in and out, device flipped
up or down) into script calls.
.P
This program must be run in background by user.
For example, it can be activated at session starting.
.SH FILES
.B $HOME/.erawrim
.RS 4
the root database
.RE
.P
.B $HOME/.erawrim/log
.RS 4
the log file
.RE
.P
.B $HOME/.erawrim/annuaire
.RS 4
the aliases between RFID id and symbolic names given by user
.RE
.P
.B $HOME/.erawrim/ztamps/
.RS 4
this directory contains the id of currently visible ztamps
.RE
.P
.B $HOME/.erawrim/endroit.sh
.RS 4
the script called when
.B Mir:ror
is flipped up
.RE
.P
.B $HOME/.erawrim/envers.sh
.RS 4
the script called when
.B Mir:ror
is flipped down
.RE
.P
.B $HOME/.erawrim/<ztamp_alias>/pose.sh
.RS 4
the script called when the associated ztamp is put
.RE
.P
.B $HOME/.erawrim/<ztamp_alias>/retire.sh
.RS 4
the script called when the associated ztamp is poped
.RE
.P
.B $HOME/.erawrim/<ztamp_alias>/times
.RS 4
the number of times the associated ztamp was inserted
.RE
.P
.B $HOME/.erawrim/<ztamp_alias>/lasttime
.RS 4
the timestamp of the last insertion of the associated ztamp
.RE
.P
.B $HOME/.erawrim/defaut/pose.sh
.RS 4
the script called when an unknown ztamp is put
.RE
.P
.B $HOME/.erawrim/defaut/retire.sh
.RS 4
the script called when an unknown ztamp is poped
.RE
.SH AUTHORS
Guilhem Bonnefille  <guilhem.bonnefille@gmail.com>

