.TH REF_LECT 1 "02 Jui 2012"
.SH NAME
ref\-lect\fP \- Mir:ror userspace driver (D-Bus service)

.SH SYNOPSIS
.B reflectd
.RI [options]
.SH DESCRIPTION
.B reflectd
is a userspace driver for the
.B Mir:ror
RFID USB device.
It translates all events (RFID tag in and out, device flipped
up or down).
.P
This program must be run by a user with reading permissions on /dev/hidraw*.
.P
Running
.B reflectd
without any argument, will automatically detect the right device to use and
will also try to connect to system D-Bus message bus.
.P
This program is a service and is not normally run directly by user.
It should be started by 
.B init
or by 
.B dbus\-daemon
via service description.
.SH OPTIONS
.B --system
Attach 
.B reflectd
to the system message bus
.P
.B --session
Attach 
.B reflectd
to the user's session message bus
.P
.B \-?,--help
Show the help message
.P
.SH FILES
.B /dev/hidraw*
the devices checked for 
.B Mir:ror
attached device
.SH AUTHORS
Guilhem Bonnefille  <guilhem.bonnefille@gmail.com>

